version: "3"

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - ./sftp/vendor:/home/vendor
      - ./sftp/ssh_host_rsa_key:/home/vendor/.ssh/keys/ssh_host_rsa_key
    ports:
      - "2222:22"
    command: vendor::1001

  namenode:
    image: bde2020/hadoop-namenode
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
    volumes:
      - ./hadoop/namenode:/hadoop/dfs/name
      - ./hadoop/home:/home
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop/hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode
    container_name: datanode1
    volumes:
      - ./hadoop/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop/hadoop.env
    depends_on:
      - namenode

  datanode2:
    image: bde2020/hadoop-datanode
    container_name: datanode2
    volumes:
      - ./hadoop/datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop/hadoop.env
    depends_on:
      - namenode

  datanode3:
    image: bde2020/hadoop-datanode
    container_name: datanode3
    volumes:
      - ./hadoop/datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop/hadoop.env
    depends_on:
      - namenode

  resourcemanager:
    image: bde2020/hadoop-resourcemanager
    container_name: resourcemanager
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864"
    env_file:
      - ./hadoop/hadoop.env
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3

  nodemanager:
    image: bde2020/hadoop-nodemanager
    container_name: nodemanager
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop/hadoop.env
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3

  historyserver:
    image: bde2020/hadoop-historyserver
    container_name: historyserver
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    volumes:
      - ./hadoop/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop/hadoop.env
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3

  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - ./clickhouse:/var/lib/clickhouse